### PR TITLE
Add script to generate reversed RTL text wordstrbox files

### PR DESCRIPTION
**Pull request by Shreeshrii**
Fixes problem for RTL languages with earlier script as reported in https://github.com/tesseract-ocr/tesseract/issues/2669#issuecomment-559106006

### CODE REVIEW

**Comment by Shreeshrii** [comment]
[test.gt.txt](https://github.com/tesseract-ocr/tesstrain/files/3906763/test.gt.txt)

test

**Comment by Shreeshrii** [comment]
Currently fonts_dir and fontname are hardcoded in the script. While idelayy it should be a font that can represent 100% of the gt text, it doesn't really matter as we are only interested in the box file.

`--strip_unrenderable_words=false ` should ensure that complete gt is represented in the charbox.

@stweil You can check using a sample from https://github.com/OpenITI/

**Comment by Shreeshrii** [comment]
Please feel free to modify the code to improve/optimize it.

**Comment by Shreeshrii** [comment]
@kba Thank you for your suggestion to use an emoji character for the substitution.  I have done that here.

**Comment by Shreeshrii** [comment]
As per Ray even for RTL languages the processing is done in LTR order. So there is  some code which reverses the input to LTR and at end reverses the output to RTL. 

I have no idea where this is done.  

By using text2image with the groundtruth txt (RTL) the box file is generated in required reverse order (LTR) using a dummy font (since we want to use the scanned image). And then the extracted groundtruth (LTR) is used for a wordstr box file for scanned image.

**Comment by wrznr** [comment]
@Shreeshrii Thanks for your explanations

> processing is done in LTR order

Makes sense. I think that is the default also for `OCRopus` and its successors.

> the box file is generated in required reverse order

Alternatively, we could reverse the text in Python and generate the box files as in `generate_wordstr_box.py`, right? Maybe, we could even reuse the script with a corresponding RTL switch.

**Comment by Shreeshrii** [comment]
That would be great.

**Comment by Shreeshrii** [comment]
>I think that is the default also for OCRopus and its successors.

Do you know if the source data for the Arabic model for OCRopus is available?

**Comment by wrznr** [comment]
Are you referring to a specific model?

**Comment by Shreeshrii** [comment]
Closing as https://github.com/tesseract-ocr/tesstrain/pull/137 provides a cleaner and more elegant solution.

**Pull request closed without merging**
