### PR TITLE
From stweil's custom makefile - calculate MAX_ITERATIONS from EPOCHS

### PR DESCRIPTION
**Pull request by Shreeshrii**
See https://github.com/tesseract-ocr/tesstrain/issues/157#issuecomment-615873731 for the patch

### CODE REVIEW

**Review by kba — APPROVED** [review]

**Comment by stweil** [comment]
I did not suggest that modification myself because it requires an existing `list.train`. That means it is not a general solution, and it is very likely that people will get unexpected results.

So we need a better solution to really support epochs. Maybe all programs which use the iteration parameter (`lstmtraining`, others?) can be enhanced to allow either a number (for iterations) or a number followed by `epochs` (for epochs).

**Comment by Shreeshrii** [comment]
Even if not merged, keeping this code in the PR makes it easier to find :-)

**Comment by zdenop** [comment]
Please use wiki for taking notes not issue tracker or PR.

**Comment by stweil** [comment]
Pull request https://github.com/tesseract-ocr/tesseract/pull/3236 allows a more stable implementation. With that change, we either need only an update of the `tesstrain` documentation because a negative value for `MAX_ITERATIONS` is then interpreted as epochs. Or we can add an `EPOCH` parameter which is forwarded to a negative `MAX_ITERATIONS`.

**Comment by Shreeshrii** [comment]
>we can add an EPOCH parameter which is forwarded to a negative MAX_ITERATIONS.

I would prefer this option. Thanks!

**Comment by Shreeshrii** [comment]
Closing, in favor of https://github.com/tesseract-ocr/tesstrain/pull/228

**Pull request closed without merging**
