### PR TITLE
DNM- Add support for different types of languages and finetune options - including option to train from text files

### PR DESCRIPTION
**Pull request by Shreeshrii**

### CODE REVIEW

**Comment by Shreeshrii** [comment]
```
 make training MODEL_NAME=san START_MODEL=script/Devanagari  LANG_TYPE=Indic FINETUNE_TYPE=Impact


 make training MODEL_NAME=san START_MODEL=script/Devanagari  LANG_TYPE=Indic FINETUNE_TYPE=Plus

 make training MODEL_NAME=san START_MODEL=script/Devanagari  LANG_TYPE=Indic FINETUNE_TYPE=Layer
```

**Comment by Shreeshrii** [comment]
Attached is a zip file with box/tif pairs and also tif and ground truth files that can be used for finetuning the above case - `san` from `script/Devanagari`. 
Finetuning can also be tried with `san` from `san` or `hin`.

[san-ground-truth.zip](https://github.com/tesseract-ocr/tesstrain/files/3570795/san-ground-truth.zip)

**Comment by wrznr** [comment]
@Shreeshrii May we add the sample data you provide to the test data in this repo?

**Comment by Shreeshrii** [comment]
>May we add the sample data you provide to the test data in this repo?

Sure.

**Comment by Shreeshrii** [comment]
Noticed couple of problems with current PR.

1. WordStr box files seem to be creating incorrect unicharset i.e. W o r d S t r is getting added to unicharset.

2. all-boxes is a concatenation of ALL box files, that is becoming very large. In my current test it is over 70 MB. 

I have marked this PR as Do not merge.

**Comment by Shreeshrii** [comment]
It can further be modified to add functionatity of training from text and fonts.

Please see https://github.com/tesseract-ocr/tesstrain/issues/93#issue-492026547

**Comment by wrznr** [comment]
@Shreeshrii Could you pls. rebase to the current master and check whether your problem persists?

**Comment by Shreeshrii** [comment]
@wrznr This PR has become too unwieldy for review because of addition of many options.

I suggest leaving this as reference for the time being and reviewing https://github.com/tesseract-ocr/tesstrain/pull/118 instead. Once that is OKed, then the rest can be added.

**Comment by stweil** [comment]
I updated the PR to fix some conflicts.

**Comment by Shreeshrii** [comment]
See https://github.com/wincentbalin/pytesstrain/blob/master/pytesstrain/cli/create_ground_truth.py for a script to Create single-line ground truth files from source file or directory.

**Comment by Shreeshrii** [comment]
See https://github.com/cmroughan/kraken_generated-data/blob/master/tools/count_chars.py to get a character count from the training_text.

**Pull request closed without merging**
