### PR TITLE
Fixed "UnicodeEncodeError"

### PR DESCRIPTION
**Pull request by mikylucky**
added .encode to char to fix UnicodeEncodeError throwed from example data.

Using provided example data, make training threw "UnicodeEncodeError: 'ascii' codec can't encode character '\xcf' in position 0: ordinal not in range(128)"

### CODE REVIEW

**Comment by stweil** [comment]
Could it be that this problem only occurs with Python 3.6, but not with Python 3.7? I recently noticed it, too, but only on Ubuntu Bionic with Python 3.6, not on Debian Buster with Python 3.7.

**Comment by stweil** [comment]
It now no longer throws `UnicodeEncodeError`, but did you have a look on the generated files? In my test, they look like this:

    b'N' 0 0 2074 136 0
    b'e' 0 0 2074 136 0
    b'c' 0 0 2074 136 0

**Comment by zdenop** [comment]
function `encode()` return `bytes` and no string, so IMO this is not correct fix.

**Comment by mikylucky** [comment]
> function `encode()` return `bytes` and no string, so IMO this is not correct fix.

It fixed the issue for me

**Comment by stweil** [comment]
How did your `.box` files look like after that fix?

**Comment by mikylucky** [comment]
> How did your `.box` files look like after that fix?

This is an example box

`b'i' 0 0 976 47 0
b'c' 0 0 976 47 0
b'h' 0 0 976 47 0
b' ' 0 0 976 47 0
b'd' 0 0 976 47 0
b'e' 0 0 976 47 0`

**Comment by stweil** [comment]
Your result:

    b'i' 0 0 976 47 0
    b'c' 0 0 976 47 0
    b'h' 0 0 976 47 0
    b' ' 0 0 976 47 0
    b'd' 0 0 976 47 0
    b'e' 0 0 976 47 0

Correct result:

    i 0 0 976 47 0
    c 0 0 976 47 0
    h 0 0 976 47 0
      0 0 976 47 0
    d 0 0 976 47 0
    e 0 0 976 47 0

**Comment by stweil** [comment]
@mikylucky, I just added a different fix to Git master. Please try that.

**Comment by mikylucky** [comment]
> @mikylucky, I just added a different fix to Git master. Please try that.

Works like a charm!

**Pull request closed without merging**
