### PR TITLE
Bug Fix: generate_line_box.py should NOT throw an error when the number lines in GT file is equal to one

### PR DESCRIPTION
**Pull request by abhishekthanki**

### CODE REVIEW

**Comment by kba** [comment]
Eek, good catch! @abhishekthanki I think the same problem exists in the other generate_*.py files. Can you fix the comparison there as well, please? Thanks.

**Comment by abhishekthanki** [comment]
@kba Sure!

**Comment by abhishekthanki** [comment]
@kba Done!

**Review by stweil — APPROVED** [review]
Thanks a lot.

**Pull request merged**
